apiVersion: v2
publisher: ms-vscode
name: powershell
version: latest
type: VS Code extension
displayName: PowerShell
title: PowerShell
description: Develop PowerShell scripts in Visual Studio Code!
icon: /v3/images/ms-vscode-powershell-icon.png
category: Debuggers
repository: 'https://github.com/PowerShell/vscode-powershell.git'
firstPublicationDate: '2021-02-25'
latestUpdateDate: '2021-04-23'
spec:
  containers:
    - image: 'quay.io/jcallen/che-plugin-sidecar:powershell'
      name: vscode-powershell
      memoryLimit: 4096M
      cpuLimit: 1500m
  extensions:
    - 'https://github.com/PowerShell/vscode-powershell/releases/download/v2020.9.0-preview/PowerShell-Preview-2020.9.0.vsix'
